version: "3.7"

services: 
    web:
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes: 
            - ./:/var/www/html/
            - ./apache.conf:/etc/apache2/sites-available/000-default.conf
        ports: 
            - 8001:80
        networks:
          - book_store 
    mysql:
        image: mysql:5.7.20
        ports:
            - 3308:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: default
            MYSQL_USER: default
            MYSQL_PASSWORD: secret
        volumes:
            - ./db:/var/lib/mysql
        networks: 
            - book_store

networks: 
    book_store:
        name: book_store